name: Shopify Lighthouse CI
on: [push]
jobs:
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Lighthouse
      uses: shopify/lighthouse-ci-action@v1
      with:
        access_token: ${{ Lighthouse.SHOP_ACCESS_TOKEN }}
        store: ${{ Lighthouse.SHOP_STORE }}
        password: ${{ Lighthouse.SHOP_PASSWORD }}